# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Document.create(title: "arquivo1.pdf", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eget feugiat ex. In ultricies augue neque, molestie faucibus erat congue sit amet. In fermentum dolor vitae nisi rutrum, at pulvinar nisl bibendum. Suspendisse sapien ipsum, finibus non elit eu, vulputate eleifend dolor. Pellentesque nec bibendum nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam cursus ligula ut facilisis pharetra. Curabitur eu est dapibus, ultricies sapien id, sollicitudin erat. Aenean sodales lorem non leo pellentesque egestas. Duis sollicitudin quam a turpis placerat ornare. Integer semper tincidunt metus, in sollicitudin est ultricies in. Nulla sit amet ultrices nisi. Quisque sed magna non orci imperdiet auctor.")
Document.create(title: "arquivo2.pdf", content: "Curabitur rutrum et diam ac dapibus. Praesent egestas luctus tristique. Vestibulum volutpat tellus sed erat varius, ac vestibulum nibh iaculis. Nullam tortor odio, cursus at tellus vitae, sollicitudin finibus lacus. Quisque tristique augue sit amet tellus feugiat, nec eleifend purus condimentum. Pellentesque et quam quis dolor tempor egestas in eu nisl. Sed urna nulla, porttitor in ligula nec, mollis posuere enim. Fusce venenatis varius ante vel eleifend. Integer bibendum a erat vel venenatis. Curabitur eget egestas arcu, sagittis egestas nibh. Donec sit amet mauris nec libero euismod mattis eu sit amet nibh. Maecenas massa lorem, ullamcorper pharetra aliquam in, volutpat a risus. Aliquam feugiat velit purus, sit amet placerat leo tristique non. Nulla a nunc efficitur, maximus neque a, efficitur nulla. Suspendisse pellentesque, odio sed bibendum efficitur, nibh sem eleifend urna, eget tincidunt lorem turpis quis odio.")
Document.create(title: "arquivo3.pdf", content: "Phasellus eget leo rutrum quam sodales dignissim. Integer non nisi sapien. Nulla facilisi. Curabitur interdum purus sit amet arcu elementum, id venenatis sapien lacinia. Quisque tellus felis, hendrerit id turpis non, vulputate convallis arcu. Nulla eu elementum libero. Vivamus suscipit nisi ac viverra viverra. Ut egestas lobortis congue. Sed at leo in odio tincidunt rhoncus.")
Document.create(title: "arquivo4.pdf", content: "Morbi pulvinar quam at vulputate semper. Nullam ornare ut metus malesuada sagittis. Vestibulum eleifend velit elit, consequat commodo nulla volutpat at. Sed vitae risus eleifend, scelerisque mauris eget, efficitur elit. Mauris sollicitudin enim ac nisi maximus facilisis. Ut et leo in lorem luctus rhoncus. Cras arcu est, aliquam et justo sit amet, tincidunt malesuada neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.")
Document.create(title: "arquivo5.pdf", content: "Pellentesque tempus a lectus id dapibus. Proin non tortor pharetra, varius magna quis, suscipit odio. Mauris non leo interdum, sodales tortor et, vestibulum libero. Suspendisse vel dapibus neque. Etiam non elit sapien. Sed semper risus eros, quis lobortis massa auctor quis. Fusce luctus, lectus ac tincidunt vehicula, neque purus commodo nisl, ac ultricies felis metus eget turpis.")
